version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "aws-lambda-poc-cf"
        Alias: "Dev"
        CurrentVersion: "$LATEST"
        TargetVersion: "$LATEST"